base_url = "https://journal.cheapnightbot.me"
title = "Cheap Nightbot - Journal "
description = "hohoi ~ welcome, me Cheap Nightbot (a boiled potato !!), and this is my corner of the internet where I share my thoughts and daily ins & outs."
compile_sass = false
minify_html = true
generate_feeds = true
default_language = "en"
theme = "anemone-ness"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Cheap Nightbot"
display_author = true

favicon = "favicon.jpeg"

default_theme = "dark"
list_pages = false
twitter_card = true
